- name: Upgrade system
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Enable RPM Fusion Free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
    state: present

- name: Enable RPM Fusion Nonfree
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
    state: present

